# Custom Grounding DINO Training Configuration
# Optimized for warehouse pallet detection

# Model Configuration
model:
  name: "grounding-dino-base"
  pretrained_model: "IDEA-Research/grounding-dino-base"
  checkpoint_path: null  # Path to resume from checkpoint
  
  # Architecture settings
  backbone: "swin_B_384_22k"
  position_embedding: "sine"
  num_queries: 900
  
  # Text encoder settings
  text_encoder_type: "bert-base-uncased"
  max_text_len: 256

# Dataset Configuration
dataset:
  name: "warehouse_pallets"
  data_root: "training/data/processed"
  
  # Class configuration
  classes: ["pallet", "wooden_pallet", "plastic_pallet", "stacked_pallet"]
  num_classes: 4
  
  # Text prompts for training
  text_prompts:
    - "wooden pallet on warehouse floor"
    - "plastic pallet in warehouse"
    - "stacked pallets"
    - "pallet wrapped in plastic"
    - "wooden skid on concrete floor"
    - "shipping pallet"
  
  # Data augmentation
  augmentation:
    horizontal_flip: 0.5
    vertical_flip: 0.0
    rotation: 15  # degrees
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    
  # Image preprocessing
  image_size: [800, 1333]  # [min_size, max_size]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Training Configuration
training:
  # Basic settings
  batch_size: 4  # Adjust based on GPU memory
  num_epochs: 50
  gradient_accumulation_steps: 4
  
  # Learning rate schedule
  optimizer: "AdamW"
  learning_rate: 1e-4
  weight_decay: 1e-4
  lr_scheduler: "MultiStepLR"
  lr_milestones: [30, 40]
  lr_gamma: 0.1
  
  # Loss configuration
  loss_weights:
    classification: 2.0
    bbox_regression: 5.0
    giou: 2.0
    
  # Gradient clipping
  max_grad_norm: 0.1
  
  # Mixed precision training
  use_amp: true
  
  # Checkpoint settings
  save_every_n_epochs: 5
  keep_last_n_checkpoints: 3
  
  # Early stopping
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: "val_loss"

# Validation Configuration
validation:
  eval_every_n_epochs: 2
  batch_size: 8
  
  # Metrics to track
  metrics:
    - "mAP"
    - "mAP_50"
    - "mAP_75"
    - "precision"
    - "recall"
    - "f1_score"
  
  # Confidence thresholds for evaluation
  confidence_thresholds: [0.1, 0.15, 0.2, 0.25, 0.3]
  nms_threshold: 0.5

# Hardware Configuration
hardware:
  # GPU settings
  device: "cuda"
  num_gpus: 1
  distributed: false
  
  # Memory optimization
  gradient_checkpointing: true
  dataloader_num_workers: 4
  pin_memory: true
  
  # Precision settings
  precision: "fp16"  # fp16, fp32, or bf16

# Logging and Monitoring
logging:
  # Experiment tracking
  use_wandb: true
  wandb_project: "warehouse-pallet-detection"
  wandb_entity: null  # Your wandb username
  
  # Local logging
  log_dir: "training/logs"
  log_level: "INFO"
  
  # Metrics logging frequency
  log_every_n_steps: 50
  save_images_every_n_epochs: 5
  
  # What to log
  log_gradients: false
  log_parameters: false
  log_images: true

# Output Configuration
output:
  model_dir: "training/models"
  checkpoint_dir: "training/models/checkpoints"
  final_model_dir: "training/models/final"
  
  # Model export formats
  export_formats: ["pytorch", "onnx"]
  
  # Inference optimization
  optimize_for_inference: true
  quantization: false

# Specific Warehouse Optimizations
warehouse_specific:
  # Camera-specific settings
  fisheye_correction: true
  
  # Object size constraints (in pixels)
  min_object_size: 32
  max_object_size: 800
  
  # Aspect ratio constraints
  min_aspect_ratio: 0.5
  max_aspect_ratio: 3.0
  
  # Confidence calibration
  calibrate_confidence: true
  
  # Multi-scale training
  multiscale_training: true
  scale_range: [0.8, 1.2]

# Advanced Training Techniques
advanced:
  # Knowledge distillation
  use_knowledge_distillation: false
  teacher_model: null
  distillation_alpha: 0.7
  
  # Self-training with pseudo-labels
  use_pseudo_labeling: false
  pseudo_label_threshold: 0.9
  
  # Test-time augmentation
  use_tta: false
  tta_scales: [0.9, 1.0, 1.1]
  
  # Model ensemble
  use_ensemble: false
  ensemble_models: []

# Debugging and Development
debug:
  # Development mode
  dev_mode: false
  quick_test: false  # Use small subset for quick testing
  
  # Visualization
  visualize_predictions: true
  save_prediction_images: true
  
  # Profiling
  profile_training: false
  profile_inference: false
  
  # Validation
  validate_data_loading: true
  check_gradients: false
