appearance_thresh: 0.3
fuse_score: true
gmc_method: sparseOptFlow
match_thresh: 0.5
max_age: 250
min_hits: 10
model: yolov8n-cls.pt
new_track_thresh: 0.6
proximity_thresh: 0.4
track_buffer: 200
track_high_thresh: 0.2
track_low_thresh: 0.05
tracker_type: botsort
with_reid: true
